# Generated by Django 4.2.7 on 2025-02-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REVIEW', 'Needs Review')], default='REVIEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence_scores',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detected_objects',
            field=models.TextField(default='[]'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status'], name='detection_d_status_c8cd09_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['timestamp'], name='detection_d_timesta_80736f_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['product'], name='detection_d_product_b7a738_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['batch_number'], name='detection_d_batch_n_9cc3f0_idx'),
        ),
        migrations.AddField(
            model_name='detection',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.product'),
        ),
    ]
